### ISSUE TITLE
Crashes with unhandled exception

### ISSUE THREAD

**Issue by probonopd** [ab77/proxy-socks#1]
Crashes with unhandled exception

https://travis-ci.org/AppImage/appimage.github.io/builds/408193033#L647

```
{ Error: Cannot find module '/home/travis/.proxy-socks/config.json'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/run/firejail/appimage/.appimage-9915/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/run/firejail/appimage/.appimage-9915/resources/app.asar/main.js:63:16)
    at Object.<anonymous> (/run/firejail/appimage/.appimage-9915/resources/app.asar/main.js:389:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32) code: 'MODULE_NOT_FOUND' }
1080
{ Error: Cannot find module '/home/travis/.proxy-socks/config.json'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/run/firejail/appimage/.appimage-9915/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/run/firejail/appimage/.appimage-9915/resources/app.asar/main.js:73:20)
    at Object.<anonymous> (/run/firejail/appimage/.appimage-9915/resources/app.asar/main.js:389:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32) code: 'MODULE_NOT_FOUND' }
undefined
{ Error: Cannot find module '/home/travis/.proxy-socks/config.json'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/run/firejail/appimage/.appimage-9915/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/run/firejail/appimage/.appimage-9915/resources/app.asar/main.js:81:25)
    at Object.<anonymous> (/run/firejail/appimage/.appimage-9915/resources/app.asar/main.js:389:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module '/home/travis/.proxy-socks/config.json'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/run/firejail/appimage/.appimage-9915/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/run/firejail/appimage/.appimage-9915/resources/app.asar/main.js:88:21)
    at Object.<anonymous> (/run/firejail/appimage/.appimage-9915/resources/app.asar/main.js:389:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module '/home/travis/.proxy-socks/config.json'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/run/firejail/appimage/.appimage-9915/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/run/firejail/appimage/.appimage-9915/resources/app.asar/main.js:95:21)
    at Object.<anonymous> (/run/firejail/appimage/.appimage-9915/resources/app.asar/main.js:389:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32) code: 'MODULE_NOT_FOUND' }
{ username: 'tunnel', host: 'localhost', port: 22 }
Xlib:  extension "RANDR" missing on display ":99".
Electron's autoUpdater does not support the 'linux' platform
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.normalize (path.js:1217:5)
    at WebContents.mainWindow.webContents.once (/run/firejail/appimage/.appimage-9915/resources/app.asar/main.js:151:30)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at WebContents.emit (events.js:211:7)
```

Reference:
https://github.com/AppImage/appimage.github.io/pull/742

**Comment by ab77** [comment]
I've not tested the Linux builds, so I am not sure. It shouldn't crash, although if you are booting it in a headless environment, there may be other issues. Does it work on a proper Linux desktop?

**Comment by ab77** [comment]
Closing due to inactivity.
